version: '3'

services:
  # web-back:
  #  container_name: crunchy_api
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  env_file:
  #    - .env
  #  ports:
  #    - "127.0.0.1:9990:80"
  #  depends_on:
  #    - cache

  # cache:
  #  container_name: crunchy_keydb
  #  image: eqalpha/keydb

  meilisearch:
    image: getmeili/meilisearch
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - meilisearch-storage:/data.ms
    restart: always

volumes:
  meilisearch-storage:
